[package]
name = "pwm_host"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pwm_protocol = {"path" = "../pwm-protocol"}
serialport = "4.2"
clap = { version = "3.2.6", features = ["derive"] }
